// src/Queue.svelte
<script>
    // components
    import QueueItem from './QueueItem.svelte'
    //store
    import { queue } from './stores'

    // functions
    import selectFiles from './backend/selectFiles'

    let queueArray = []
    const unsubscribe = queue.subscribe(value => ( queueArray = value));

    function startQueue(){
        queue.update(state => [...state].map((item, index) => {
            if (index === 0) {
                item.status = 'current'
            }
            return item
        }))
    }

    function clearQueue(){
        queue.update(() => [])
    }

</script>
<div class="my-6 mb-2 w-full lg:w-6/12 ">
    <ul class="songs-lists relative left-0 py-4">
        {#if queueArray.length}
            {#each queueArray as queue}
                <QueueItem item={queue} />
            {/each}
        {/if}
    </ul>
    <div class="flex justify-center items-center px-12 mt-4">
        <button  on:click|once={startQueue} type="button" class="text-white flex items-center justify-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-lg focus:outline-none focus:shadow-outline transition ease-in-out duration-150 mr-4 bg-green-500 hover:bg-green-700">
            iniciar
        </button>
        <button on:click|once={clearQueue} type="button" class="flex items-center justify-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-lg text-gray-900 hover:text-gray-600 focus:outline-none focus:shadow-outline transition ease-in-out duration-150 bg-white" >
            clear
        </button>
    </div>
</div>

// src/components/Queue/index.jsx
import React from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { Creators as actions } from '../../store/queue'

import QueueItem from './QueueItem'
import {Button} from '../formComponents'

function Queue() {
    const dispatch = useDispatch()
    const files = useSelector(state => state.queue)

    function clearStore() {
        dispatch(actions.clear())
    }

    function startQueue() {
        dispatch(actions.startQueue())
    }

    if (!files.length) {
        return null
    }

    return (
        <div className="my-6 mb-2 w-full lg:w-6/12 ">
            <ul className="songs-lists relative left-0 py-4">
                {files.sort((a, b) => a.song.localeCompare(b.song)).map(file => <QueueItem key={file.song} file={file} />)}
            </ul>
            <div className="flex justify-center items-center px-12 mt-4">
                <Button label="iniciar" onClick={startQueue} type="button" />
                <Button label="clear" onClick={clearStore} type="button" />
            </div>
        </div>
    )
}

export default Queue
