// src/QueueItem.svelte
<script>
    import { afterUpdate } from 'svelte'
    import saveWaveform, {convertSongToBuffer} from './backend/waveform'
    import convertToMp3 from './backend/convertToMp3'
    import drawAudio from './helpers/waveform'

    //store
    import { queue } from './stores'

    let progressBar;

    // props
    export let item = {}
    $: song = item.song
    $: name = item.name
    $: status = item.status

    function err(error) {
        console.error({ error })
    }

    function updateStatus(status){
      queue.update(state => [...state].map((item) => {
        if (item.song === song) {
          item.status = status
        }
        return item
      }))
    }

    function handleProgress(value){
        progressBar.style.setProperty('--progress', value / 100)
        queue.update(state => [...state].map((item) => {
            if (item.song === song) {
                item.progress = status
            }
            return item
        }))

      if(value === 100){
         updateStatus('done')

         queue.update(state => {

            const nextItem = [...state].find(({ status }) => status === 'waiting')
            if (!nextItem) {
                return state
            }
            const qs = [...state].filter(({song}) => song !== nextItem.song)
            return  [...qs, {...nextItem, status: 'current'}]
        })
      }

    }

    // life cicles
    afterUpdate(() => {

        if (status === 'current') {
            requestIdleCallback(async () => {
                const buff = await convertSongToBuffer(song)
                const wave = await drawAudio(buff)
                saveWaveform(song, JSON.stringify(wave))
            })

            requestIdleCallback(async () => {
                updateStatus('processing')
                convertToMp3({ file: song, onProgress: handleProgress, err })
            })

        }
	});


</script>

<li class="relative py-3 text-sm leading-5">
    <div class="flex justify-between items-center">
        <span class="text-white text-xs opacity-25 capitalize">
            {name.replace(/[[\]-]+/g, ' ')}
        </span>
    </div>
    <div class="progressbar w-full" bind:this={progressBar} />
</li>

// src/components/Queue/QueueItem.jsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Creators as actionsQueue } from '../../store/queue'

import dataurl from 'dataurl'
import fs from 'fs'
import path from 'path'

// modules
import convertToMp3 from '../../backend/convertToMp3'
import saveWaveform from '../../backend/saveWaveform'
import drawAudio from '../../helpers/waveform'

const convertSongToBuffer = filePath => {
    const songPromise = new Promise((resolve, reject) => {
        fs.readFile(filePath, (err, data) => {
            if (err) {
                reject(err)
            }
            resolve(dataurl.convert({ data, mimetype: 'audio/mp3' }))
        })
    })
    return songPromise
}

function QueueItem({ file }) {
    const [songObj, setSong] = useState({})

    const [fileName] = useState(() => {
        const fileName = path.basename(file.song)
        const extension = path.extname(file.song)
        return path.basename(fileName, extension)
    })

    const progressBar = useRef(null)
    const files = useSelector(state => state.queue)
    const dispatchProgress = useDispatch()

    useEffect(() => {
        const song = files.find(e => e.song === file.song)
        setSong(song)
    }, [file, files])

    const handleProgress = useCallback(
        value => {
            if (progressBar.current) {
                requestAnimationFrame(() => {
                    const { song } = songObj
                    progressBar.current.style.setProperty(
                        '--progress',
                        value / 100
                    )
                    dispatchProgress(
                        actionsQueue.updateProgress({ song, progress: value })
                    )
                    if (value === 100) {
                        dispatchProgress(
                            actionsQueue.updateStatus({ song, status: 'done' })
                        )
                        dispatchProgress(actionsQueue.updateQueue())
                    }
                })
            }
        },
        [dispatchProgress, songObj]
    )

    useEffect(() => {
        function err(error) {
            console.error({ error })
        }

        const { song, status } = songObj

        if (status === 'current') {
            requestIdleCallback(async () => {
                const buff = await convertSongToBuffer(song)
                const wave = await drawAudio(buff)
                saveWaveform(song, JSON.stringify(wave))
            })

            requestIdleCallback(() => {
                convertToMp3({ song, onProgress: handleProgress, err })
                dispatchProgress(
                    actionsQueue.updateStatus({ song, status: 'processing' })
                )
            })
        }
    }, [songObj.status, songObj, handleProgress, dispatchProgress])

    return (
        <li className="px-12 relative py-3 text-sm leading-5">
            <div className="flex justify-between items-center">
                <span className="text-white text-xs opacity-25 capitalize">
                    {fileName.replace(/[\[\]-]+/g, ' ')}
                </span>
            </div>
            <div
                className={`progressbar w-10/12 ${songObj.status}`}
                ref={progressBar}
            />
        </li>
    )
}

export default React.memo(QueueItem)
